### ISSUE TITLE
go build issue in fabric 1.0

### ISSUE THREAD

**Issue by souvikdey2** [fabric-composer/fabric-composer#609]
I downloaded the hyperledger repository from https://github.com/hyperledger/fabric.git
And trying to compile the basic example chaincode02 and found it is not compiling with below error.
# github.com/hyperledger/fabric/vendor/github.com/miekg/pkcs11
../../../../vendor/github.com/miekg/pkcs11/pkcs11.go:29:18: fatal error: ltdl.h: No such file or directory
#include <ltdl.h>
                  ^
compilation terminated.

code :        iter, err:=stub.GetHistoryForKey(A)
It is working fine in fabric version 0.6

**Comment by sstone1** [comment]
@souvikdey2 this is not a Fabric Composer issue, please raise it against the Fabric team. They use JIRA for tracking issues, that is available from: https://jira.hyperledger.org
